project:
  type: book
  render:
    - "index.qmd"
    - "chapters/*.qmd"
  execute-dir: project  # working directory is always root of project
  output-dir: "_build/"

book:
  title: "R Basics"
  author:
    - "Nick Ulle"
    - "Wesley Brooks"
  date: now
  chapters:
    - "index.qmd"
    - "chapters/01_getting-started.qmd"
    - "chapters/02_data-structures.qmd"
    - "chapters/03_exploring-data.qmd"
    - "chapters/04_organizing_code.qmd"
    - "chapters/05_appendix.qmd"
    - "chapters/97_where-to-learn-more.qmd"
    - "chapters/98_acknowledgements.qmd"
    - "chapters/99_assessment.qmd"
  repo-url: "https://github.com/ucdavisdatalab/workshop_r_basics"
  repo-actions: [issue, source]
  sidebar:
    logo: "images/datalab-logo-full-color-rgb-1.png"
    logo-alt: "The logo of the UC Davis DataLab."
    logo-href: "https://datalab.ucdavis.edu/"

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      - text: |
          <style>
          .callout.callout-style-default .callout-body {
            padding: 0 1.5rem .2rem;
          }
          .cell-output-stdout {
            overflow-y: scroll;
            max-height: 30rem;
            margin-bottom: 0.75rem;
          }
          </style>
  pdf: default

execute:
  freeze: auto
